// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NanTingBlog.API.Services.Db;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NanTingBlog.API.Migrations
{
    [DbContext(typeof(BlogContext))]
    partial class BlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NanTingBlog.API.Dtos.Blogs.PostInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id")
                        .HasJsonPropertyName("id");

                    b.PrimitiveCollection<List<string>>("Author")
                        .HasColumnType("text[]")
                        .HasColumnName("author")
                        .HasJsonPropertyName("author");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content")
                        .HasJsonPropertyName("content");

                    b.Property<long>("CreateTime")
                        .HasColumnType("bigint")
                        .HasColumnName("createTime")
                        .HasJsonPropertyName("createTime");

                    b.Property<string>("DrawingUrl")
                        .HasColumnType("text")
                        .HasColumnName("drawingUrl")
                        .HasJsonPropertyName("drawingUrl");

                    b.Property<long>("EditTime")
                        .HasColumnType("bigint")
                        .HasColumnName("editTime")
                        .HasJsonPropertyName("editTime");

                    b.Property<string>("HTML")
                        .HasColumnType("text")
                        .HasColumnName("html")
                        .HasJsonPropertyName("html");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasJsonPropertyName("name");

                    b.PrimitiveCollection<List<string>>("Tag")
                        .HasColumnType("text[]")
                        .HasColumnName("tag")
                        .HasJsonPropertyName("tag");

                    b.HasKey("Id");

                    b.ToTable("posts");
                });
#pragma warning restore 612, 618
        }
    }
}
